### ISSUE TITLE
XcodeColors support

### ISSUE THREAD

**Issue by paulz** [jdhealy/PrettyColors#10]
Thank you for useful library!

❓ 
Does PrettyColors outputs strings that are colored in Xcode console output?

I've tried using XcodeColors, which works well with manually inserted color codes.
https://github.com/robbiehanson/XcodeColors
but could not seem get it to recognize PrettyColors strings.

Escape code in resulting string:
`[fg64,64,192;` works
`[33;22m` does not

**Comment by jdhealy** [comment]
The ECMA-48 standardized ‘ANSI’ escape codes that PrettyColors outputs [aren't supported by mainline `robbiehanson/XcodeColors`](github.com/robbiehanson/XcodeColors/issues/66) (though there is a [pull request from 2014 which might be adpatable](github.com/robbiehanson/XcodeColors/pull/12).)

With the additional constraint that [Xcode 8 doesn't load in-process plugins (such as XcodeColors)](github.com/alcatraz/Alcatraz/issues/475), explicitly adopting XcodeColors’s custom syntax doesn't seem worthwhile for PrettyColors.

Thanks for the interesting question, had fun looking into this! ✨

**Comment by jdhealy** [comment]
Reopened this by accident, sorry about that 😁
