### ISSUE TITLE
SPM depends on a version tag without the "v"

### ISSUE THREAD

**Issue by gorzell** [jdhealy/PrettyColors#17]
It seems that SPM needs a version tag that isn't prefixed with "v" in order to work.

i.e. `4.0.0` not `v4.0.0`.  Luckily there is nothing that prevents git from having both tags if you don't want to just switch.  For the next release could you tag it this way?

```
swift build
Cloning https://github.com/jdhealy/PrettyColors.git
error: The dependency graph could not be satisfied. The package (https://github.com/jdhealy/PrettyColors.git) with version tag in range (4.0.0..<4.9223372036854775807.9223372036854775807) is not found. Found tags ([0.0.1, 0.0.2])
```

**Comment by jdhealy** [comment]
Good looking out, appreciate the reminder.

As the time of this writing, [the development branch](https://github.com/jdhealy/PrettyColors/tree/development) (currently on commit `6f54504`)
 is tracking the 3.0.X and SPM-conforming work. The release cut from that branch will have a version tag without the `v`.

**Comment by jdhealy** [comment]
> The release cut from that branch will have a version tag without the `v`.

https://github.com/jdhealy/PrettyColors/releases/tag/5.0.0
